# Akka picks up its license key from system property `akka.license-key`.
# We bridge from the AKKA_LICENSE_KEY env var so docker-compose / k8s can
# inject it without changing config files. Register for a free key at
# https://akka.io/key — without one the actor system terminates after ~15
# minutes ("Akka terminated. Obtain free keys at https://akka.io/key").
akka.license-key = ${?AKKA_LICENSE_KEY}
